name: ourspace_flutter
description: Production-ready OurSpace Privacy-Focused Mobile Application
publish_to: 'none'
version: 1.1.5+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.1.8
  crypto: ^3.0.3
  cryptography: ^2.7.0
  http: ^1.2.0
  web_socket_channel: ^3.0.3
  flutter_webrtc: ^1.6.0
  app_links: ^3.5.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  image_picker: ^1.1.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/app_logo.png"
  color_dark: "#000000"
  image_dark: "assets/images/app_logo.png"
  android_12:
    image: "assets/images/app_logo_android.png"
    color: "#FFFFFF"
    color_dark: "#000000"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/


